Kolab\Holiday\Infrastructure\Projection\HolidayRead:
    exclusion_policy: ALL
    properties:
        holidayId:
            type: string
            name: holidayId
        customerId:
            type: string
        start:
            type:  DateTime<'Y-m-d'>
        state:
            type: string