prooph_event_store:
    stores:
        holiday_store:
            event_store: Prooph\EventStore\Pdo\MySqlEventStore
            repositories:
                holiday:
                    repository_class: Kolab\Holiday\Infrastructure\Repository\EventStoreHolidays
                    aggregate_type: Kolab\Holiday\Domain\Holiday
                    aggregate_translator: prooph_event_sourcing.aggregate_translator

services:
    Prooph\EventStore\Pdo\MySqlEventStore:
        arguments: ['@prooph_event_store.message_factory', '@doctrine.pdo.connection', '@prooph_event_store.single_stream_strategy']

    doctrine.pdo.connection:
        class: PDO
        factory: ['@database_connection', getWrappedConnection]

    prooph_event_store.single_stream_strategy:
        class: Prooph\EventStore\Pdo\PersistenceStrategy\MySqlSingleStreamStrategy

    prooph_event_sourcing.aggregate_translator:
        class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator