prooph_service_bus:
    command_buses:
        kolab.command_bus:
            plugins: ~
            router:
                type: 'prooph_service_bus.command_bus_router'
                routes:
                    'Kolab\Holiday\Application\Command\CreateHoliday': '@kolab.holiday.create.handler'
    query_buses:
        kolab.query_bus:
            message_factory: 'prooph_service_bus.message_factory'
            plugins:
                - 'prooph_service_bus.finder_invoke_strategy'
            router:
                type: 'prooph_service_bus.query_bus_router'
                routes:
                    'Kolab\Holiday\Application\Query\ListHolidays': '@kolab.holiday.list.handler'
                    'Kolab\Holiday\Application\Query\GetHoliday': '@kolab.holiday.get.handler'
    event_buses:
        kolab.event_bus:
            plugins:
                - 'prooph_service_bus.on_event_invoke_strategy'
            router:
                type: 'prooph_service_bus.event_bus_router'
                routes:
                #    'TestArmy\Company\Domain\Event\CompanyWasDeleted':
                #        - '@test_army.project.remove_by_companyid'
services:
    kolab.holiday.create.handler:
        class: Kolab\Holiday\Application\Command\Handler\CreateHolidayHandler
        arguments: ['@holiday']
    kolab.holiday.list.handler:
        class: Kolab\Holiday\Application\Query\Handler\ListHolidaysHandler
        arguments: ['@projection.finder.holiday']
    kolab.holiday.get.handler:
        class: Kolab\Holiday\Application\Query\Handler\GetHolidayHandler
        arguments: ['@projection.finder.holiday']